In [1]:
import os
import pandas as pd 
import json
import psycopg2

In [2]:
#aggregated transaction 

path ="C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/aggregated/transaction/country/india/state/"
aggregated_trans_list = os.listdir(path)

columns1  = {"States": [], "Years":[], "Quarter":[], "Transaction_type":[],"Transaction_count":[],"Transaction_amount":[]}

for state in aggregated_trans_list:
    cur_state = path+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            A = json.load(data)
            for i in A["data"]["transactionData"]:
                name=i["name"]
                count=i["paymentInstruments"][0]["count"]
                amout=i["paymentInstruments"][0]["amount"]
                columns1["Transaction_type"].append(name)
                columns1["Transaction_count"].append(count)
                columns1["Transaction_amount"].append(amout)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))

aggregatedtransaction = pd.DataFrame(columns1) 

aggregatedtransaction["States"]=aggregatedtransaction["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggregatedtransaction["States"]=aggregatedtransaction["States"].str.replace('-',' ')
aggregatedtransaction["States"]=aggregatedtransaction["States"].str.title()
aggregatedtransaction["States"]=aggregatedtransaction["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [3]:
#aggregated user
aggregatedpath_user = "C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/aggregated/user/country/india/state/"

aggregated_user_list = os.listdir(aggregatedpath_user)

columns2  = {"States": [], "Years":[], "Quarter":[], "Brands":[],"Transaction_count":[],"Percentage":[]}

for state in aggregated_user_list:
    cur_state = aggregatedpath_user+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            B = json.load(data)
            try:
                for i in B["data"]["usersByDevice"]:
                    brand=i["brand"]
                    count=i["count"]
                    percentage=i["percentage"]
                    columns2["Brands"].append(brand)
                    columns2["Transaction_count"].append(count)
                    columns2["Percentage"].append(percentage)
                    columns2["States"].append(state)
                    columns2["Years"].append(year)
                    columns2["Quarter"].append(int(file.strip(".json")))

            except:
                pass

aggregateduser = pd.DataFrame(columns2) 

aggregateduser["States"]=aggregateduser["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggregateduser["States"]=aggregateduser["States"].str.replace('-',' ')
aggregateduser["States"]=aggregateduser["States"].str.title()
aggregateduser["States"]=aggregateduser["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [4]:
#aggregated insurance

path_agge_insure = "C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/aggregated/insurance/country/india/state/"

aggregated_insruce_list = os.listdir(path_agge_insure)

columns5  = {"States": [], "Years":[], "Quarter":[], "Transaction_type":[],"Transaction_count":[],"Transaction_amount":[]}

for state in aggregated_insruce_list:
    cur_state = path_agge_insure+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            E = json.load(data)
            
            for i in E["data"]["transactionData"]:
                name=i["name"]
                count=i["paymentInstruments"][0]["count"]
                amout=i["paymentInstruments"][0]["amount"]
                columns5["Transaction_type"].append(name)
                columns5["Transaction_count"].append(count)
                columns5["Transaction_amount"].append(amout)
                columns5["States"].append(state)
                columns5["Years"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))

aggregatedinsurance = pd.DataFrame(columns5)

aggregatedinsurance["States"]=aggregatedinsurance["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggregatedinsurance["States"]=aggregatedinsurance["States"].str.replace('-',' ')
aggregatedinsurance["States"]=aggregatedinsurance["States"].str.title()
aggregatedinsurance["States"]=aggregatedinsurance["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [5]:
#map\transaction
map_path = "C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/map/transaction/hover/country/india/state/"

map_transact_list = os.listdir(map_path)

columns3  = {"States": [], "Years":[], "Quarter":[], "Districts":[],"Transaction_count":[],"Transaction_amount":[]}

for state in map_transact_list:
    cur_state = map_path+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            C = json.load(data)
            
            for i in C["data"]["hoverDataList"]:
                    name=i["name"]
                    count=i["metric"][0]["count"]
                    amount=i["metric"][0]["amount"]
                    columns3["Districts"].append(name)
                    columns3["Transaction_count"].append(count)
                    columns3["Transaction_amount"].append(amount)
                    columns3["States"].append(state)
                    columns3["Years"].append(year)
                    columns3["Quarter"].append(int(file.strip(".json")))

maptransaction = pd.DataFrame(columns3)

maptransaction["States"]=maptransaction["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
maptransaction["States"]=maptransaction["States"].str.replace('-',' ')
maptransaction["States"]=maptransaction["States"].str.title()
maptransaction["States"]=maptransaction["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [6]:
#map\user 

map_user_path = "C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/map/user/hover/country/india/state/"

map_user_list = os.listdir(map_user_path)

columns4  = {"States": [], "Years":[], "Quarter":[], "Districts":[],"RegisteredUsers":[],"AppOpens":[]}

for state in map_user_list:
    cur_state = map_user_path+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            D = json.load(data)
            for i in D["data"]["hoverData"].items():    
                Districts=i[0]
                registeredUsers=i[1]["registeredUsers"]
                appOpens=i[1]["appOpens"]
                columns4["Districts"].append(Districts)
                columns4["RegisteredUsers"].append(registeredUsers)
                columns4["AppOpens"].append(appOpens)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))

mapuser  = pd.DataFrame(columns4)

mapuser["States"]=mapuser["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
mapuser["States"]=mapuser["States"].str.replace('-',' ')
mapuser["States"]=mapuser["States"].str.title()
mapuser["States"]=mapuser["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [7]:
#map_insrurence 
map_insurce_path = "C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/map/insurance/hover/country/india/state/"

map_insurence_list = os.listdir(map_insurce_path)

columns6  = {"States": [], "Years":[], "Quarter":[], "Districts":[],"Transaction_count":[],"Transaction_amount":[]}

for state in map_insurence_list:
    cur_state = map_insurce_path+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            F = json.load(data)
            
            for i in F["data"]["hoverDataList"]:
                    name=i["name"]
                    count=i["metric"][0]["count"]
                    amount=i["metric"][0]["amount"]
                    columns6["Districts"].append(name)
                    columns6["Transaction_count"].append(count)
                    columns6["Transaction_amount"].append(amount)
                    columns6["States"].append(state)
                    columns6["Years"].append(year)
                    columns6["Quarter"].append(int(file.strip(".json")))
                

map_insrurence   = pd.DataFrame(columns6)


map_insrurence ["States"]=map_insrurence ["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
map_insrurence ["States"]=map_insrurence ["States"].str.replace('-',' ')
map_insrurence ["States"]=map_insrurence ["States"].str.title()
map_insrurence ["States"]=map_insrurence ["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [8]:
#top_insrurence
top_insruernce_path = "C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/top/insurance/country/india/state/"

top_insrurence_lit = os.listdir(top_insruernce_path)

columns7  = {"States": [], "Years":[], "Quarter":[], "Pincodes":[],"Transaction_count":[],"Transaction_amount":[]}

for state in top_insrurence_lit:
    cur_state = top_insruernce_path+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            G = json.load(data)
            for i in G["data"]["pincodes"]:    
                entityName=i["entityName"]
                count=i["metric"]["count"]
                amount=i["metric"]["amount"]
                columns7["Pincodes"].append(entityName)
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))


top_insrurence   = pd.DataFrame(columns7)


top_insrurence ["States"]=top_insrurence ["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
top_insrurence ["States"]=top_insrurence ["States"].str.replace('-',' ')
top_insrurence ["States"]=top_insrurence ["States"].str.title()
top_insrurence ["States"]=top_insrurence ["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [9]:
#top_transaction
top_transaction_path = "C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/top/transaction/country/india/state/"

top_transaction_lit = os.listdir(top_transaction_path)

columns8  = {"States": [], "Years":[], "Quarter":[], "Pincodes":[],"Transaction_count":[],"Transaction_amount":[]}

for state in top_transaction_lit:
    cur_state = top_insruernce_path+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            H = json.load(data)
            for i in H["data"]["pincodes"]:    
                entityName=i["entityName"]
                count=i["metric"]["count"]
                amount=i["metric"]["amount"]
                columns8["Pincodes"].append(entityName)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))

top_transaction   = pd.DataFrame(columns8)


top_transaction ["States"]=top_transaction ["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
top_transaction ["States"]=top_transaction ["States"].str.replace('-',' ')
top_transaction ["States"]=top_transaction ["States"].str.title()
top_transaction ["States"]=top_transaction ["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [10]:
#top_user
top_user_path = "C:/Users/HameedS/Desktop/New folder/phonepe/pulse/data/top/user/country/india/state/"

top_user_lit = os.listdir(top_user_path)

columns9  = {"States": [], "Years":[], "Quarter":[], "Pincodes":[],"RegisteredUsers":[]}

for state in top_user_lit:
    cur_state = top_user_path+state+"/"
    agg_year_list = os.listdir(cur_state)   

    for year in agg_year_list:
        cur_year = cur_state+year+"/"
        agg_file_list = os.listdir(cur_year)
        
        for file in agg_file_list:
            cur_file = cur_year+file
            data = open(cur_file,"r")

            H = json.load(data)
            for i in H["data"]["pincodes"]:    
                entityName=i["name"]
                registeredUsers=i["registeredUsers"]               
                columns9["Pincodes"].append(entityName)
                columns9["RegisteredUsers"].append(registeredUsers)                
                columns9["States"].append(state)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))

Top_user = pd.DataFrame(columns9)


Top_user ["States"]=Top_user ["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
Top_user ["States"]=Top_user ["States"].str.replace('-',' ')
Top_user ["States"]=Top_user ["States"].str.title()
Top_user ["States"]=Top_user ["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [12]:

#table createion    SQL CONNECT
#aggregated transaction
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query2 = '''create table if not exists aggregated_transaction(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Transaction_type varchar (250),
                                                   Transaction_count bigint,
                                                    Transaction_amount bigint)'''

cursor.execute(create_query2)
mydb.commit()

insertquery2 = '''insert into aggregated_transaction(States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)

values(%s,%s,%s,%s,%s,%s)'''
data=aggregatedtransaction.values.tolist()
cursor.executemany(insertquery2,data)
mydb.commit()

# aggregateduser table
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query3 = '''create table if not exists aggregated_user(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Brands varchar (250),
                                                   Transaction_count bigint,
                                                    Percentage float)'''

cursor.execute(create_query3)
mydb.commit()

insertquery3 = '''insert into aggregated_user(States, Years, Quarter,Brands, Transaction_count, Percentage)

values(%s,%s,%s,%s,%s,%s)'''
data=aggregateduser.values.tolist()
cursor.executemany(insertquery3,data)
mydb.commit()
#aggregated insurance table
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query1 = '''create table if not exists aggregated_insurance(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Transaction_type varchar (250),
                                                   Transaction_count bigint,
                                                    Transaction_amount bigint)'''

cursor.execute(create_query1)
mydb.commit()

insertquery1 = '''insert into aggregated_insurance(States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)

values(%s,%s,%s,%s,%s,%s)'''
data=aggregatedinsurance.values.tolist()
cursor.executemany(insertquery1,data)
mydb.commit()
# map_transaction  table
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query5 = '''create table if not exists Map_transaction(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Districts varchar (250),
                                                   Transaction_count bigint,
                                                    Transaction_amount bigint)'''

cursor.execute(create_query5)
mydb.commit()

insertquery5 = '''insert into Map_transaction(States, Years, Quarter,Districts, Transaction_count, Transaction_amount)

values(%s,%s,%s,%s,%s,%s)'''
data=maptransaction.values.tolist()
cursor.executemany(insertquery5,data)
mydb.commit()
# map_user  table
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query6 = '''create table if not exists Map_user(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Districts varchar (250),
                                                   RegisteredUsers  bigint,
                                                   AppOpens bigint)'''

cursor.execute(create_query6)
mydb.commit()

insertquery6 = '''insert into Map_user(States, Years, Quarter,Districts, RegisteredUsers,AppOpens)

values(%s,%s,%s,%s,%s,%s)'''
data=mapuser.values.tolist()
cursor.executemany(insertquery6,data)
mydb.commit()

# Map_insruence  table
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query4 = '''create table if not exists Map_insruence(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Districts varchar (250),
                                                   Transaction_count bigint,
                                                    Transaction_amount bigint)'''

cursor.execute(create_query4)
mydb.commit()

insertquery4 = '''insert into Map_insruence(States, Years, Quarter,Districts, Transaction_count, Transaction_amount)

values(%s,%s,%s,%s,%s,%s)'''
data=map_insrurence.values.tolist()
cursor.executemany(insertquery4,data)
mydb.commit()

# top_insrurence  table
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query7 = '''create table if not exists top_insrurence(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Pincodes int,
                                                   Transaction_count  bigint,
                                                   Transaction_amount bigint)'''

cursor.execute(create_query7)
mydb.commit()

insertquery7 = '''insert into top_insrurence(States, Years, Quarter,Pincodes, Transaction_count,Transaction_amount)

values(%s,%s,%s,%s,%s,%s)'''
data=top_insrurence.values.tolist()
cursor.executemany(insertquery7,data)
mydb.commit()

# top_transaction  table
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query8 = '''create table if not exists top_transaction(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Pincodes int,
                                                   Transaction_count  bigint,
                                                   Transaction_amount bigint)'''

cursor.execute(create_query8)
mydb.commit()

insertquery8 = '''insert into top_transaction(States, Years, Quarter,Pincodes, Transaction_count,Transaction_amount)

values(%s,%s,%s,%s,%s,%s)'''
data=top_transaction.values.tolist()
cursor.executemany(insertquery8,data)
mydb.commit()
# top_user  table
mydb = psycopg2.connect(host="localhost",
                        user="postgres",
                        password="0040",
                        database="phonepe_data",
                        port="5432")
cursor = mydb.cursor()

create_query9 = '''create table if not exists top_user(States varchar(250),
                                                 Years int, 
                                                 Quarter int,
                                                  Pincodes int,
                                                   RegisteredUsers  bigint)'''

cursor.execute(create_query9)
mydb.commit()

insertquery9 = '''insert into top_user(States, Years, Quarter,Pincodes, RegisteredUsers)

values(%s,%s,%s,%s,%s)'''
data=Top_user.values.tolist()
cursor.executemany(insertquery9,data)
mydb.commit()